default: &default
  adapter: mysql2
  encoding: utf8
  database: playbook_basketball_<%= Rails.env %>
  pool: 5
  username: root
  password:
  host: localhost
  encoding: utf8mb4

development:
  <<: *default
  socket: /tmp/mysql.sock

test:
  <<: *default
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
